
/**
 * This is the implementation of Generate class the messages are generated inside the SyntaxAnalyser
 * class hence the need to simply throw the exception up the stack in this class
 * @author Chris Foxley-Evans 32879415
 * @version 0.0.5
 */
public class Generate extends AbstractGenerate {

    /**
     * This method throws the exception up the call stack to be dealt with later on
     * @param token This is the token where the Analyser failed
     * @param explanatoryMessage This is the helpful error message generated by the analyser
     * @throws CompilationException
     */
    @Override
    public void reportError(Token token, String explanatoryMessage) throws CompilationException {
        throw new CompilationException(explanatoryMessage);
    }
}
